version: '3.8'

services:
  frontend:
    image: ghcr.io/shuffle/shuffle-frontend:nightly
    hostname: shuffle-frontend
    networks:
      - shuffle
    env_file: .env
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s

  backend:
    image: ghcr.io/shuffle/shuffle-backend:nightly
    hostname: shuffle-backend
    networks:
      - shuffle
      - swarm_executions
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shuffle-apps:/shuffle-apps
      - shuffle-files:/shuffle-files
    env_file: .env
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s

  orborus:
    image: ghcr.io/shuffle/shuffle-orborus:nightly
    hostname: shuffle-orborus
    networks:
      - shuffle
      - swarm_executions
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      - SHUFFLE_APP_SDK_TIMEOUT=300
      - BASE_URL=http://shuffle-backend:5001
      - SHUFFLE_STATS_DISABLED=true
      - SHUFFLE_SWARM_CONFIG=run
      - SHUFFLE_WORKER_IMAGE=ghcr.io/shuffle/shuffle-worker:latest
      - SHUFFLE_WORKER_SERVER_URL=http://shuffle-workers:33333
      - SHUFFLE_SWARM_NETWORK_NAME=shuffle_swarm_executions
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      placement:
        preferences:
          - spread: node.id

  opensearch:
    image: opensearchproject/opensearch:3.0.0
    hostname: shuffle-opensearch
    env_file: .env
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m
      - bootstrap.memory_lock=false
      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
      - cluster.initial_master_nodes=shuffle-opensearch
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=shuffle-cluster
      - node.name=shuffle-opensearch
      - node.store.allow_mmap=false
      - discovery.seed_hosts=shuffle-opensearch
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - shuffle-database:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - shuffle
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  load-balancer:
    image: nginx:alpine
    ports:
      - "3001:80"
      - "3443:443"
    networks:
      - shuffle
    volumes:
      - ./nginx-main.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s

  memcached:
    image: memcached:latest
    hostname: shuffle-cache
    networks:
      - shuffle
    command: memcached -m 1024 -c 2500
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  # NFS-backed volumes that are shared across all swarm nodes
  shuffle-apps:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_MASTER_IP},rw,nfsvers=4
      device: "${NFS_MASTER_IP}:/srv/nfs/shuffle-apps"

  shuffle-files:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_MASTER_IP},rw,nfsvers=4
      device: "${NFS_MASTER_IP}:/srv/nfs/shuffle-files"

  shuffle-database:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_MASTER_IP},rw,nfsvers=4
      device: "${NFS_MASTER_IP}:/srv/nfs/shuffle-database"

networks:
  shuffle:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: "1500"
  swarm_executions:
    driver: overlay
    attachable: true
