version: '3.8'

services:
  frontend:
    image: ghcr.io/shuffle/shuffle-frontend:nightly
    hostname: shuffle-frontend
    networks:
      - shuffle
    env_file: .env
    deploy:
      replicas: ${SWARM_NODE_COUNT}
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      placement:
        max_replicas_per_node: 1

  backend:
    image: ghcr.io/shuffle/shuffle-backend:nightly
    hostname: shuffle-backend
    networks:
      - shuffle
      - swarm_executions
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shuffle-apps:/shuffle-apps
      - shuffle-files:/shuffle-files
    env_file: .env
    deploy:
      replicas: ${SWARM_NODE_COUNT}
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      placement:
        max_replicas_per_node: 1

  orborus:
    image: ghcr.io/shuffle/shuffle-orborus:nightly
    hostname: shuffle-orborus
    networks:
      - shuffle
      - swarm_executions
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      - SHUFFLE_APP_SDK_TIMEOUT=300
      - BASE_URL=http://shuffle-backend:5001
      - SHUFFLE_STATS_DISABLED=true
      - SHUFFLE_SWARM_CONFIG=run
      - SHUFFLE_WORKER_IMAGE=ghcr.io/shuffle/shuffle-worker:latest
      - SHUFFLE_APP_REPLICA=3
      - SHUFFLE_WORKER_SERVER_URL=http://shuffle-workers:33333
      - SHUFFLE_SWARM_NETWORK_NAME=shuffle_swarm_executions
    deploy:
      replicas: ${SWARM_NODE_COUNT}
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      placement:
        preferences:
          - spread: node.id

  opensearch:
    image: opensearchproject/opensearch:3.0.0
    env_file: .env
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms6g -Xmx6g
      - bootstrap.memory_lock=false
      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=shuffle-cluster
      - node.name=shuffle-opensearch-{{.Task.Slot}}
      - node.store.allow_mmap=false
      - discovery.seed_hosts=tasks.shuffle_opensearch
      - cluster.initial_master_nodes=${OPENSEARCH_INITIAL_MASTERS}
      - network.host=0.0.0.0
      - action.auto_create_index=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - shuffle

    volumes:
      - shuffle-database:/usr/share/opensearch/data
    deploy:
      replicas: ${OPENSEARCH_REPLICAS}
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
      placement:
        max_replicas_per_node: 1
        preferences:
          - spread: node.id
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G

  load-balancer:
    image: nginx:alpine
    ports:
      - "3001:80"
      - "3443:443"
    networks:
      - shuffle
    volumes:
      - nginx-config:/nginx-config:ro
    command: sh -c "cp /nginx-config/nginx-main.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    deploy:
      replicas: ${SWARM_NODE_COUNT}
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      placement:
        max_replicas_per_node: 1

  memcached:
    image: memcached:latest
    hostname: shuffle_memcached
    networks:
      - shuffle
    env_file: .env
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  # NFS volumes - shared across all swarm nodes (NFSv3 with pinned mountd)
  shuffle-apps:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_MASTER_IP},nfsvers=3,proto=tcp,rw,soft,intr,port=2049,mountport=51771,resvport,nolock,timeo=600,retrans=2"
      device: ":/srv/nfs/shuffle-apps"

  shuffle-files:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_MASTER_IP},nfsvers=3,proto=tcp,rw,soft,intr,port=2049,mountport=51771,resvport,nolock,timeo=600,retrans=2"
      device: ":/srv/nfs/shuffle-files"

  shuffle-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/shuffle/shuffle-database

  nginx-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_MASTER_IP},nfsvers=3,proto=tcp,ro,soft,intr,port=2049,mountport=51771,resvport,nolock,timeo=600,retrans=2"
      device: ":/srv/nfs/nginx-config"


networks:
  shuffle:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: "1500"
  swarm_executions:
    driver: overlay
    attachable: true